### ISSUE TITLE
HTMLtoTIFF.run() gets stuck when converting mhtml, htm to TIFF

### ISSUE THREAD

**Issue by tmhungcode** [aspose-html/Aspose.HTML-for-Java#3]
I checked out this repo. In HTMLtoTIFF, I replaced input.html with these 2 files in the attachment, HTML - Wikipedia.mhtml, and Aspose API - Wikipedia.htm. The application ran forever and not produced any TIFF files.

[html.zip](https://github.com/aspose-html/Aspose.HTML-for-Java/files/4627252/html.zip)

**Comment by tahir-manzoor** [comment]
@tmhung88 

Please use the latest version of [Aspose.HTML for Java 21.12](https://downloads.aspose.com/html/java/new-releases/aspose.html-for-java-21.12/) to avoid this issue.
